language: node_js
services:
  - mongodb
  - elasticsearch
node_js:
  - "8"
before_install:
  - sudo rm -vf /etc/apt/sources.list.d/*riak*
  - sudo apt-get update
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.2.2.deb && sudo dpkg -i --force-confnew elasticsearch-6.2.2.deb && sudo service elasticsearch restart
before_script:
  - sleep 30
